feedbacks/urls.py
from django.conf.urls import patterns, include, url
from feedbacks import views

urlpatterns = patterns('',
    url(r'^$', views.FeedbackView.as_view(), name='feedback'),
    url(r'^$', views.CallOrderView.as_view(), name='call_order'),
)

powder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url
from django.contrib import admin
from powder import views
from feedbacks.views import FeedbackView, CallOrderView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'powder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^call_order/', CallOrderView.as_view(), name="call_order" ),
    url(r'^feedbacks/', FeedbackView.as_view(), name="feedback" ),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedbacks/models.py
# -*- coding: utf-8 -*- 
from django.db import models
from django.contrib.auth.models import User
import datetime


class Feedback(models.Model):
    name = models.CharField( max_length=225, verbose_name=u'Ваше имя')
    subject = models.CharField(max_length=255, verbose_name=u'тема')
    message = models.TextField(verbose_name=u'сообщение')
    from_email = models.EmailField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
		return self.subject

class CallOrder(models.Model):
    name = models.CharField( max_length=100, verbose_name=u'Ваше имя')
    subject = models.CharField(max_length=100, verbose_name=u'тема')
    phone = models.IntegerField(max_length=100, verbose_name=u'Ваш телефон')
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
		return self.subject

products/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse

class Powder(models.Model):
    name = models.CharField(
        max_length=70)
    powder_type = models.CharField(
        max_length=70, choices=((u'Для Цветного Белья', "Color"),(u'Для Белого Белья', "White")))
    packing = models.CharField(
        max_length=70, choices=(('3kg', '3'),('15kg', '15')))
    auto = models.CharField(
        max_length=70, choices=((u'Автомат', "yes"),(u'Ручная стирка', "no")), default='no')
    price_wholesale = models.FloatField(
        verbose_name=u"Цена опт.")
    price_retail = models.FloatField(
        verbose_name=u"Цена розница")
    description = models.TextField()
    photo = models.ImageField(
        upload_to='products', default = "/images/pexels-photo-45718.jpeg")
    availability = models.BooleanField(default=True)
    
    def __unicode__(self):
		return self.name

class AboutPowder(models.Model):
    name = models.CharField(
        max_length=70)
    description = models.TextField()
    propose = models.TextField(default="Malve")

    def __unicode__(self):
		return self.name

class NavButton(models.Model):
    name = models.CharField(
        max_length=70)
    number = models.PositiveIntegerField()

    def __unicode__(self):
		return self.name

class Contact(models.Model):
    phone_1 = models.IntegerField(
        max_length=15)
    phone_2 = models.IntegerField(
        max_length=15)
    phone_3 = models.IntegerField(
        max_length=15)
    email = models.EmailField()
    photo = models.ImageField(
        upload_to='products_img', null=True)
    
    def __unicode__(self):
		return self.email

feedbacks/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from feedbacks.models import Feedback, CallOrder

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'

class CallOrderForm(forms.ModelForm):
    class Meta:
        model = CallOrder
        fields = '__all__'

products/forms.py
# -*- coding: utf-8 -*- 
from django import forms
from products.models import Powder, PowderOrder


class PowderOrderForm(forms.ModelForm):
    class Meta:
        model = PowderOrder
        fields = '__all__'
        data = {'name': Powder}
        form = PowderOrder(data)

feedbacks/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.mail import mail_admins
from feedbacks.models import Feedback, CallOrder
from feedbacks.forms import FeedbackForm, CallOrderForm


class FeedbackView(CreateView):
    model = Feedback
    template_name = 'feedback.html'
    form_class = FeedbackForm
    context_object_name = 'form'
    success_url = reverse_lazy('index')
    #success_message = u"Thank you for your feedback! We will keep in touch with you very soon!"
    
    def get_context_data(self, **kwargs):
        context = super(FeedbackView, self).get_context_data(**kwargs)
        context['title'] = "Обратная связь"
        return context 

    def form_valid(self, form):
        feedback = form.save()
        messages.success(self.request, u"Спасибо за Ваше сообщение! Наш менеджер перезвонит Вам!")
        mail_admins(feedback.subject, feedback.message)
        return super(FeedbackView, self).form_valid(form)

class CallOrderView(CreateView):
    model = CallOrder
    template_name = 'call_order.html'
    form_class = CallOrderForm
    context_object_name = 'form'
    success_url = reverse_lazy('coopiration')
    
    def get_context_data(self, **kwargs):
        context = super(CallOrderView, self).get_context_data(**kwargs)
        context['title'] = "Заказать звонок"
        return context 

    def form_valid(self, form):
        call_order = form.save()
        messages.success(self.request, u"Спасибо за Ваше сообщение! Наш менеджер перезвонит Вам!")
        mail_admins(call_order.name, call_order.phone, call_order.message)
        return super(CallOrderView, self).form_valid(form)

powder/views.py
# -*- coding: utf-8 -*- 
from django.views.generic import TemplateView
from products.models import Powder, AboutPowder, NavButton, Contact


class IndexView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['powder'] = Powder.objects.all()
        context['about_powder'] = AboutPowder.objects.all()
        context['nav_buttons1'] = NavButton.objects.get(number=1)
        context['nav_buttons2'] = NavButton.objects.get(number=2)
        context['nav_buttons3'] = NavButton.objects.get(number=3)
        context['nav_buttons4'] = NavButton.objects.get(number=4)
        context['nav_buttons5'] = NavButton.objects.get(number=5)
        context['contacts'] = Contact.objects.all()
        context['email_us'] = NavButton.objects.get(number=5)
        return context

products/views.py
# -*- coding: utf-8 -*- 
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from products.models import Powder


class PowderListView(ListView):
    model = Powder
    
    def get_queryset(self):
        products = Powder.objects.all()
        return products

class PowderDetailView(DetailView):
    model = Powder
    template_name = 'products/detail.html'
    context_object_name = 'powder'
    
    def get_context_data(self, **kwargs):
        context = super(PowderDetailView, self).get_context_data(**kwargs)
        #context['options'] = Option.objects.filter(service = self.object)
        return context

templates/call_order.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Заказать звонок</title>

  </head>
  <body>
    <div>
		<div class="panel panel-default">
  		<div><h2>{{ title }}</h2>
      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <h4>{{ message }}</h4>
          {% endfor %}
        </div>
        {% endif %}
      </div>   
<a href="{% url 'index' %}"><i class="fa fa-wrench"></i> назад на главную</a>
<form method="post">
          {% csrf_token %}   

        <h4 class="modal-title" id="exampleModalLabel">Напишите Ваше сообщение</h4>
            <label for="recipient-name" class="control-label">{{ form.as_p }}</label>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        
         <button type="submit" class="btn btn-primary">Отправить</button>
          </div>
    </div>
  </div>
</div>
         </form>
  </div>
</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>	
	  <script src="{% static 'js/m_auto.js' %}"></script>   	
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
</html>

templates/feedback.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Обратная Связь</title>

  </head>
  <body>
    <div>
		<div class="panel panel-default">
  		<div><h2>{{ title }}</h2>
      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <h4>{{ message }}</h4>
          {% endfor %}
        </div>
        {% endif %}
      </div>  
    <a href="{% url 'index' %}"><i class="fa fa-wrench"></i> назад на главную</a> 
<form method="post">
          {% csrf_token %}   

        <h4 class="modal-title" id="exampleModalLabel">Напишите Ваше сообщение</h4>
            <label for="recipient-name" class="control-label">{{ form.as_p }}</label>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        
         <button type="submit" class="btn btn-primary">Отправить</button>
          </div>
    </div>
  </div>
</div>
         </form>
  </div>
</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>	
	  <script src="{% static 'js/m_auto.js' %}"></script>   	
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
</html>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
 <html lang="en" data-type="background" data-speed="7">
  <head>
    <meta charset="utf-8" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Malve-Made in Germany</title>
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/m_auto_navbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/notcourier.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-7243260-2']);
_gaq.push(['_trackPageview']);
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
    </script>
  </head>
  <body>
    <div class="container">
      <div class="main-header">
		<div class="cbp-af-inner">
		  <h4 class="h4"><a class="h4" href="{% url 'index' %}">Malve</h4>          
		  <nav class="nav-main">      
			<a href="#about_powder">{{ nav_buttons1.name }}</a>                        
			<a href="#products:powder_list">{{ nav_buttons2.name }}</a>         
            <a href="#contacts">{{ nav_buttons3.name }}</a>
            <a class="feedback" href="{% url 'feedback' %}"><i class="fa fa-send"></i> {{ nav_buttons5.name }}</a>
		  </nav>
		</div>
	  </div>
    </div>
    <div class="background-color-main-content" data-type="background" data-speed="7">
            <h3>MADE IN GERMANY</h3>
            <p>Пральні порошки з Німеччини</p>
      </div>
      <a name="about_powder"><div class="about_powder">
        {% for about_powder in about_powder %}
        <p class="about_powder_name">{{ about_powder.name }}</p>
        <p class="about_powder_description">{{ about_powder.description }}</p>
        {% endfor %}
      </div></a>
      <a name="products:powder_list"><div class="product_powder" data-type="background" data-speed="7">
          {% for about_powder in about_powder %}
          <p class="powder_propose">{{ about_powder.propose }}</p>
          {% endfor %}
          {% for powder in powder %}
          <table class="product_table">
    <tr>
        <td rowspan="2"><h1>{{ powder.name }}</h1>
          <img class="malve-img" src="{{ powder.photo.url }}">
          </td>
        <td><ul class="powder_characteristic">
            <li>{{ powder.powder_type }}</li>
            <li>{{ powder.auto }}</li>
            <li>{{ powder.packing }}</li>
          </ul></td>
        <td rowspan="2"><p class="powder_description">{{ powder.description }}</p></td>
    </tr>
    <tr>
        <td><li id="powder_price">{{ powder.price_retail }} грн.</li></td>
    </tr>
</table>
          {% endfor %}
      </div></a>
      <a name="contacts"><div class="contacts">
        <p class="email_title">Пишіть нам на e-mail</p>
        {% for contacts in contacts %}
        <a href="{% url 'feedback' %}"><p class="contacts_email">{{ contacts.email }}</p></a>
        <p class="phone_title">Наші контакти</p>
        <p class="contacts_phone">{{ contacts.phone_1 }}; {{ contacts.phone_2 }}; {{ contacts.phone_3 }}</p>
        {% endfor %}
      </div></a>
      <div class="cooperate">
        <p class="cooperate_info"><a class="btn-appointment" href="{% url 'call_order' %}" role="button">заказать звонок</a></p>
      </div>
      <div class="footer">
        <p class="footer_info">Наши Контакти</p>
      </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/m_auto.js' %}"></script>	
    <script src="{% static 'js/m_auto_navigation.min.js' %}"></script>  
    <script src="{% static 'js/background.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
  </body>
</html>